# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e8b9d01bcdff2c8115ea3049836bbc0a5b55e24f522e82f710f3799e39990e80a9ca9fc78e1699f55400ea983b6d0975d93d15f037c9c42b0bc7bcdba813bfff

test:
  secret_key_base: b7b95682f68e35e8702efe80243bc7d65799a053a19abd6c7246992fd914b5b4ff62ac69ee86a0e19bc96c775096adad6ce77f99361625bf1813e54eb45f2717

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
